name:                sample-yaml-th
version:             0.1.0.0
github:              "matsubara0507/sample-yaml-th"
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/matsubara0507/sample-yaml-th#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- yaml

library:
  source-dirs: src
  other-modules:
  - Sample.Config.Internal
